name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@v1

  coverage:
    uses: sxzz/workflows/.github/workflows/coverage.yml@v1
    needs: unit-test
    permissions:
      id-token: write
